#!/bin/bash

if [ $# -ne 2 ]
then
    echo "usage: $0 <points file> <output .png>"
    exit
fi

plot=$( mktemp )

xmin=$( head -n 1 $1 | cut -d ' ' -f 1 )
ymin=$( head -n 1 $1 | cut -d ' ' -f 2 )
xmax=$( tail -n 1 $1 | cut -d ' ' -f 1 )
ymax=$( tail -n 1 $1 | cut -d ' ' -f 2 )

echo "
set terminal png
set output '$2'
set autoscale xfix
set autoscale yfix
set yrange [] reverse
set xtics ($xmin, $xmax)
set ytics ($ymin, $ymax)
set format x '%.0f'
set format y '%.0f'
set tics font 'arial, 10'

plot '$1' using 1:2 notitle with lines linecolor rgb 'black'
" >> $plot

gnuplot $plot
rm $plot
