#!/bin/bash

trap control_c SIGINT

control_c()
# run if user hits control-c
{
    rm -f $tout
    rm -f $out
    rm -f $stat
    exit $?
}

time=/usr/bin/time

DIR=$(dirname $0)
swsharpn=$DIR/../bin/swsharpn
swsharpout=$DIR/../bin/swsharpout

printf "%-13s %-13s | " "query" "target"
printf "%-20s %-20s %-20s %-10s | " "solve" "find" "recn" "total"
printf "%-10s | " "mem (MB)"
printf "%-14s | " "prunned"
printf "%-21s %-21s | " "start" "end"
printf "%-13s | " "score"
printf "%-13s %-13s %-13s %-13s" "length" "identity" "similarity" "gaps"
echo

out=$(mktemp)
tout=$(mktemp)
stat=$(mktemp)

while read line
do

    in1=$(echo $line | cut -d " " -f 1)
    in2=$(echo $line | cut -d " " -f 2)

    n1=$(basename $in1)
    n2=$(basename $in2)

    echo "processing: " $n1 $n2 1>&2 
    
    dump=$n1"-"$n2

    $time -o $tout -f "%e %M" $swsharpn -i $in1 -j $in2 --outfmt dump --out $dump > $out
    $swsharpout -i $dump --outfmt 'stat' --out $stat

    ts=$(grep "STOP:src/sw_end_data_gpu.cu" $out | cut -d " " -f 2 | paste -sd ",")
    tf=$(grep "STOP:src/sw_find_start_gpu.cu" $out | cut -d " " -f 2 | paste -sd ",")
    tr=$(grep "STOP:src/reconstruct.c" $out | cut -d " " -f 2 | paste -sd ",")
    tt=$(cat $tout | cut -d" " -f1)
    m=$(echo "scale = 3; $(cat $tout | cut -d " " -f2) / 1025.0" | bc)
    prn=$(grep "Pruned percentage" $out | cut -d " " -f 4 | paste -sd ",")

    len=$(grep "Length" $stat | cut -d " " -f 3)
    idn=$(grep "Identity" $stat | awk -F' ' '{print $3}' | cut -d "/" -f 1 )
    sim=$(grep "Similarity" $stat | awk -F' ' '{print $3}' | cut -d "/" -f 1)
    gap=$(grep "Gaps" $stat | awk -F' ' '{print $3}' | cut -d "/" -f 1)
    scr=$(grep "Score" $stat | cut -d " " -f 3)
    qrys=$(grep "Query" $stat | cut -d " " -f 3 | tr -d "(,")
    qrye=$(grep "Query" $stat | cut -d " " -f 4 | tr -d ")")
    tgts=$(grep "Target" $stat | cut -d " " -f 3 | tr -d "(,")
    tgte=$(grep "Target" $stat | cut -d " " -f 4 | tr -d ")")

    printf "%-13s %-13s | " $n1 $n2
    printf "%-20s %-20s %-20s %-10s | " $ts $tf $tr $tt
    printf "%-10s | " $m
    printf "%-14s | " $prn
    printf "%-21s %-21s | " "($qrys, $tgts)" "($qrye, $tgte)"
    printf "%-13s | " $scr
    printf "%-13s %-13s %-13s %-13s" $len $idn $sim $gap
    echo
    
done < $1

rm $tout
rm $out
rm $stat
